name: chingu_bookfinder_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  base_api:
    path: ./packages/base_api
  bloc: ^8.1.4
  equatable: ^2.0.3
  firebase_api:
    path: ./packages/firebase_api
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.1.0
  go_router: ^13.1.0
  google_books_api:
    path: ./packages/google_books_api
  html: ^0.15.0
  reactive_forms: ^13.0.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  mocktail: ^0.2.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
