name: firebase_api
description: Firebase Api
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.0

dev_dependencies:
  coverage: ^1.0.3
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  firebase_core_platform_interface: 4.4.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.2.1
  mocktail: ^0.3.0

dependency_overrides:
  firebase_core_platform_interface: 4.4.1
