name: firebase_api
description: Firebase Api
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  coverage: ^1.0.3
  fake_cloud_firestore: ^3.0.2
  firebase_auth_mocks: ^0.14.1
  firebase_core_platform_interface: 4.4.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.4

dependency_overrides:
  firebase_core_platform_interface: 4.4.1
