name: chingu_bookfinder_flutter

on: [pull_request, push]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.4
      min_coverage: 50
      runs-on: macos-latest
